### PR TITLE
Replaced custom typefaces with Arial Family, styling changes to links

### PR DESCRIPTION
**Pull request by dalena**
Made changes to type based on comments from web design team

### CODE REVIEW

**Comment by hsab** [comment]
I think we should link/import the font. This is what I see on linux and it isn't arial:
Screenshot_20200527_161740

**Comment by hsab** [comment]
@blerchin should we also use the opp to address #65?

**Comment by blerchin** [comment]
@hsab yes pls, at least the font aspect. If there is static build-related stuff, might be better to put that in another PR.

**Comment by brysonian** [comment]
Just a note that i'm pretty sure serving arial like that is illegal. But while you are at it, these days you just need WOFF.

**Comment by hsab** [comment]
@blerchin @dalena 
Added Arial Black to our public folder (WOFF, WOFF2, EOT, TTF, SVG).
If we go with Blaine's alternative we can simply replace these. 
Using [fontfaceobservor](https://github.com/bramstein/fontfaceobserver) to detect font loading. This is neat library and with really small footprint (3.5KB minified and 1.3KB gzipped).

The font itself is 54KB at it's lowest (woff2) and 194kb at it's highest (svg format for iOS 4.1). Most browsers end up using Woff2. 

ffobservor waits for 3 seconds to display the title, if the font doesn't load by then, well... the title needs to be shown, albeit with the fallback ~title~ font. 

I added the font-face to `variables.css`. Seemed like the appropriate place for it.

**Comment by hsab** [comment]
> Just a note that i'm pretty sure serving arial like that is illegal. But while you are at it, these days you just need WOFF.

Yeah, I really didn't realize this bc of the ubiquity of Arial. But even if Microsoft doesn't strike us down, Kyle will :laughing:

**Comment by hsab** [comment]
In other news...
https://github.com/search?l=&q=filename%3A%22Arial+Black.ttf%22&type=Code

**Comment by hsab** [comment]
Screenshot_20200527_215000

**Comment by blerchin** [comment]
That's a big font!
For comparison, Days One, which is our current header, is 14kb

**Review by blerchin — APPROVED** [review]
I'd like to see a smaller font if possible, but LGTM

**Comment by hsab** [comment]
> I'd like to see a smaller font if possible, but LGTM

It probably has a large subset of the unicode glyphs. I can try and cut it down to A-Z/0-1? Would that work?

**Comment by blerchin** [comment]
> It probably has a large subset of the unicode glyphs. I can try and cut it down to A-Z/0-1? Would that work?

if it doesn't take too much time, that would be great!

**Comment by hsab** [comment]
```
145K ariblkmin.sfd
 33K ariblkmin.svg
 32K ariblkmin.ttf
 20K ariblkmin.woff
 16K ariblkmin.woff2
```
sfd is for font-forge we can remove it for production.

**Pull request merged**
