### PR TITLE
Collapse anim paper

### PR DESCRIPTION
**Pull request by hsab**
Similar functionality to [collapse-animation](https://github.com/blerchin/dma-20-mfa-show/tree/collapse-animation). 100% paperjs/window based. 

### Modifies:
- https://github.com/blerchin/dma-20-mfa-show/blob/6e6db2eae0f4c58b7201a95e8cd83e105253d914/src/BlobField/blobs.js#L1

#### Slight syntactic changes to:
- https://github.com/blerchin/dma-20-mfa-show/blob/8fd8c6cee21c1bf345d226092a40b1b17c05a076/src/BlobField/index.js#L1

### Notes
 - #### Uses requestAnimationFrame for frame based tweening:
   - https://github.com/blerchin/dma-20-mfa-show/blob/719bf51b89882268bbe8e373440dbda9d840a907/src/BlobField/blobs.js#L222-L224

 - #### Supports for both immediate _or_ animated resizing of blobs on homepage
   - https://github.com/blerchin/dma-20-mfa-show/blob/719bf51b89882268bbe8e373440dbda9d840a907/src/BlobField/blobs.js#L177-L190

### CODE REVIEW

**Comment by blerchin** [comment]
This looks great! Way better than my attempt.

In the future, would be best to branch off of master since this includes a bunch of unrelated changes from `artist-pages`. I'll check in with Lauren in the morning and make sure we are good to merge that, then we can go ahead with this.

**Comment by brysonian** [comment]
I was thinking i'd merge artist-pages into here after those other pages are added, then pull this into master instead. I didn't want lauren to have to redo all those pages so this seemed the way to prevent that. But i'm game for whatever is easiest for everyone.

**Comment by hsab** [comment]
Yeah I figured that would be a problem. Just wanted to test this with actual content and the scrollbar toggling. 

Let's wait on merging. I will checkout a new branch from master and recommit the changes. It's only 2 files so it should be pretty smooth.

**Comment by hsab** [comment]
Closing in favor of https://github.com/blerchin/dma-20-mfa-show/pull/29

**Pull request closed without merging**
