### PR TITLE
fix videos not autoplaying

### PR DESCRIPTION
**Pull request by blerchin**
for mysterious reasons we can't set `muted` on videos in the Video component using react syntax. But it does work by javascript 🤷‍♀️ 
Also fixes some unrelated mistakes in `ProjectDescription`

### CODE REVIEW

**Comment by brysonian** [comment]
I HATE THIS BUG. https://github.com/facebook/react/issues/6544

**Comment by blerchin** [comment]
When rendering on the client we'll use the property since it was determined that modifying the attribute didn't actually affect the video. We must set it as `node.muted = true|false`, so you don't see that reflected in the attribute.

_Originally posted by @zpao in https://github.com/facebook/react/issues/6544#issuecomment-217977564_

AMAZING
I love this

**Review by hsab — APPROVED** [review]

**Comment by hsab** [comment]
@blerchin  unrelated to this, but I realize deploy builds are taking longer and looking at the log it shows that it installs npm modules on every single build. Is this necessary?

**Comment by blerchin** [comment]
@hsab Netlify usually caches dependencies, so yeah I'm not sure why it's not doing that. Introducing the react-snap static build dramatically increased build times as well. Not sure if that process somehow also prevented deps from being cached? I haven't really bothered to look into it since I realized the cost isn't that big a deal. But it is annoying....

Screen Shot 2020-05-26 at 1 35 36 AM

**Pull request merged**
