### PR TITLE
Avoid crashes on mobile when pinch-to-zooming

### PR DESCRIPTION
**Pull request by blerchin**
#72

### CODE REVIEW

**Comment by blerchin** [comment]
good news! Setting the `fadeOut` option in ProjectCover makes the crash state impossible to access. Or, at least, very very difficult. So I feel good about enabling this. Will also have positive implications for performance on all devices.
This does mean we will lose the blurry background while scrolling through projects, which is somewhat of a compromise. Thoughts?

**Comment by hsab** [comment]
Sounds good to me. @dalena ?

**Review by hsab — APPROVED** [review]

**Comment by hsab** [comment]
@blerchin btw how did you debug this?

**Review by dalena — APPROVED** [review]
:< RIP, that's really sad. It was nice while it lasted

**Comment by blerchin** [comment]
Combination of things. But ultimately figured out the solution with ngrok to forward localhost to my phone, and the Safari dev console while my phone is plugged into the computer. This also works with the xCode simulator, and Android has a feature where they allow you to tether your phone to Chrome.
I tend not to use that setup unless it's a really egregious bug (which this was) because it takes forever to set up. But very useful for situations like this, so you can make code changes and see effects immediately.

**Pull request merged**
