### PR TITLE
Dalena integration

### PR DESCRIPTION
**Pull request by dalena**
So, phew... with the extensive help of @hsab and @brysonian I was able to get my project files integrated onto the site. Tried to make sure that there aren't any conflicts with the rest if the site.  @blerchin @lmccart @brysonian have a look to see if there are any issues that come up from your end. 

I'm hoping to get my mp3 files hosted somewhere more reliable than github pages/github releases, but that's where my audio files are hosted as of now. I am still preparing my voiceover audio and will make some minor changes to my files before launching. Other than that, it should be complete!

### CODE REVIEW

**Comment by hsab** [comment]
@blerchin @brysonian Dalena is using jquery and howler for her project and these seem to increase the page size by 53KB. Would this be a cause for issues? Although I highly doubt it I was wondering if there's a way to deliver these only on her page.

**Comment by lmccart** [comment]
@hsab this doesn't answer your question, but it looks like the jquery is being used very minimally and could be replaced with vanilla js. I think it makes sense to keep the howler.

**Comment by blerchin** [comment]
It's possible to only deliver jquery on Dalena's page with webpack chunk splitting. But personally I'd prefer to spend that time removing jquery altogether. As Lauren mentioned it is used minimally – mostly for element lookups, which can be replaced with `document.querySelector`. The only actual use of a jquery feature I see is `fadeIn` which can be replaced with CSS transitions.

**Comment by blerchin** [comment]
@dalena  I modified this to remove all the jquery uses. I can see why you weren't excited about doing that, but ultimately everything it was doing could be replaced by <3 lines of js + CSS.
I think all the functionality is intact, but I don't know everything this code is supposed to do so I can't fully test it.

**Comment by blerchin** [comment]
Well, it's *almost* working. For some reason switching from jQuery.async to fetch is causing the dreaded Navigation TimeoutError in `react-snap`
Probably something to do with the difference in XMLHTTPRequest and fetch API in the headless browser
https://github.com/stereobooster/react-snap/issues/240

**Comment by hsab** [comment]
@blerchin looks great! Thanks for spending and hour or so on this. 🙏🏼🌹

**Comment by hsab** [comment]
@blerchin I get the following from netlify
`11:45:04 AM: Error scheduling build`

**Comment by blerchin** [comment]
@hsab huh, seems like a weird Netlify fluke
Screen Shot 2020-05-25 at 12 00 57 PM

**Comment by dalena** [comment]
@blerchin thank you so much for doing that. Everything seems to still be functioning! I'm okay with this if there is no more issues

**Review by blerchin — APPROVED** [review]
Yay! Looks good to me

**Pull request merged**
