### PR TITLE
Responsive improvements

### PR DESCRIPTION
**Pull request by blerchin**
So far:
- make `ProjectHeader` absolutely positioned on mobile so it moves away as you scroll
- set minimal pixel margins (rather than vw-relative) for header and nav on mobile viewports
- Switch columns to flexbox to avoid specifying columncount in JS. Make them stack nicely on mobile
- Adjust margins of columns. Introduce `<Spacer>` component to standardize handling of funky situations where Images and text are stacked on top of each other. Maybe not the *most* semantic approach, but it avoids having endless logic in `Image` addressing the contexts in which it is used.
- Improve responsive layout on Zeynep and Berfin pages
- Make contents of `ProjectCover` full-width on mobile

### CODE REVIEW

**Comment by blerchin** [comment]
This should address all of the issues in #54 now. Not sure it's perfect, but definitely a significant improvement.

@dalena can you look this over for style?
@brysonian I changed the css implementation of some of the components, especially `ProjectColumns`. Let me know if you see any issues with my flexbox approach, or if these changes are gonna create problematic interactions with other components anywhere.

I am still not thrilled with the way Info and Home in the nav cover the content on mobile. I was wondering about the prospect of scrolling them "backwards" off the edge of the screen so they disappear similarly to the ProjectHeader.

Example of this effect in practice:
http://aggregate.vision/route/59b2b635b4ffb8193134286a

Interested if folks think this effect would work. Or if it's bad UX to hide the nav...

**Comment by dalena** [comment]
@blerchin this is looking incredible. The entire site feels opened up. I really like the changes to the columns you made with flexbox as well. 

I'm not seeing the materials description in the project header any longer
2020-05-25 01_55_44-Window

I agree about the nav. It sits really close to the blob/project links on mobile and there's too much happening there. Would it be difficult to try implementing the scroll effect you're referencing? The other option which I also am not necessarily thrilled about is moving the Home/info nav to the top right corner. 

Also think we can get rid of the horizontal line between content and artist bio on mobile. Or should we get rid of the line completely? hmm

Last thing, there seems to be some added padding to some pages that have page columns of more than two: 

2020-05-25 01_44_59-Window

**Comment by hsab** [comment]
Screenshot_20200525-015334
Screenshot_20200525-015340

Ben this is fantastic! Thanks for the hard work. 
Some minor issues... As the photos shows there are some side margin discrepancies. 
Also the title is acting up again on home page. I think it might have to do with the app bottom margin. But not sure. I've put a video below showing the issue:
https://drive.google.com/file/d/1VihBMJjldkyFvZ9Z5q36Y_1HnYLqWEEB/view?usp=drivesdk

Nevertheless this is so much work! Thank you again

**Comment by blerchin** [comment]
Ok, I fixed the column and homepage-scrolling bugs. Good catch @hsab 

I also added the Nav reverse-scrolling behavior. IMO it's working nicely.
Bio dividing line is removed.
@dalena the materials are still showing up, just not on that page =)

If it's OK with everyone, I'd like to get this approved and rolled in asap so we avoid merge conflict hell

**Review by dalena — APPROVED** [review]
Looks great!!

**Pull request merged**
