### PR TITLE
Artist pages

### PR DESCRIPTION
**Pull request by lmccart**
here are the last two artist pages (blaine and leming). we should now be complete. just waiting on the updated image from graham, and I imagine there will be some small requests for tweaks that I can add in one more round tomorrow.

did you want to send the preview link out to the artists to review?

### CODE REVIEW

**Review by blerchin — APPROVED** [review]

**Comment by blerchin** [comment]
Yeah, I can send out a link to everyone. Do you want me to send the preview link for this PR, or merge and send the preview for `master`?

**Comment by lmccart** [comment]
@blerchin I think maybe merge and send preview for master? I don't remember, but this branch might still have the bug where it crashes after opening dalena's page due to the audio running

**Comment by lmccart** [comment]
@blerchin while I've got you here.. can you confirm website live time is 10am friday? or? thanks!

**Comment by blerchin** [comment]
I don't know where that time came from. But... sure. Seems doable.

**Comment by lmccart** [comment]
@blerchin haha me either, maybe erkki just made it up. this is just a detail for the 2pm reception email so we can say 10am, and if there's a need to push it back it's no problem.

**Comment by blerchin** [comment]
Makes sense to have a soft opening time. And that gives us time to work late Thurs night if necessary so I feel good about it.

**Comment by blerchin** [comment]
Seems like Dalena's audio is broken on this branch anyway due to the files being moved to dma servers. I will let her take care of that in the other PR.

**Pull request merged**
