### PR TITLE
add core-js and fetch polyfills and only load them where we need them

### PR DESCRIPTION
**Pull request by blerchin**
this might be my proudest webpack moment fyi

### CODE REVIEW

**Comment by blerchin** [comment]
IE11 is the big one. Also older Safari. Not our target users, I know, but I try to avoid showing anyone a blank page.
Results of a bunch of testing are here: https://github.com/blerchin/dma-20-mfa-show/issues/5

Unfortunately it seems this approach to loading polyfills is outdated and fundamentally incompatible with the chunked loader, which can do this kind of stuff automagically.

**Comment by blerchin** [comment]
I don't know if that was really worth all the effort, but our website now works pretty well in Internet Explorer!

**Comment by dalena** [comment]
If my page is actually causing issues in IE, then you can show them a video of my project, is that possible?

**Comment by blerchin** [comment]
@dalena sure we could do that. Also take a look at #5, I've been taking screenshots as I go.

**Comment by brysonian** [comment]
Gotcha, wanted to make sure i wasn't missing something. Just look at the stats for the dma site, we get between 1,500 and 9000?! IE (mostly 10) users a month? And over the past year IE is the bulk of our traffic. Shocking. Brenda must be refreshing the page a lot!

**Review by hsab — APPROVED** [review]

**Comment by brysonian** [comment]
This looks good. Doesn't core-je include a promise polyfill? Also with these concerns, is there a need for autoprefixing?

**Comment by blerchin** [comment]
@brysonian the promise polyfill at the top is due to the annoying fact that webpack's `import()` (and `require()` relies on promises, so we need to load that before we can do any lazy-loading. The promise polyfill is <1KB, not sure of the size of `core-js/promise`. Could be similar. It's not ideal but definitely better than loading all of `core-js` for everyone

**Comment by blerchin** [comment]
autoprefixing would be nice! might address some of the flexbox issues we're having

**Comment by brysonian** [comment]
Gotcha. I'll see about adding that this afternoon.

**Comment by hsab** [comment]
Ben out of curiosity how does this work with pre-rendering. 
Because I just remembered that chrome/chromium is used by puppeteer. And wonder if `modernBrowser` is always set to true. Was your browserstack testing with dev or prod builds?

**Comment by hsab** [comment]
nm. address bar says deploy, so I guess it was indeed build.

**Comment by blerchin** [comment]
If anything it should improve prerendering. There were some weird issues
with fetch that caused the downgrade a while back and this should normalize
the behavior of fetch and promises.

I am not sure if puppeteer registers as modern or no. But I don't think the
build process modifies static js at all so it shouldn't affect whether we
serve polyfills in the browser or no.

And, yeah, all my testing was on production builds. A lot of the old
browsers actually can't handle our dev build because it doesn't rewrite
`let` and `const`.
...
Ben Lerchin *(they/them/theirs)*

benlerchin.com
ben@lerchin.com
(415) 259-9358
...

**Comment by brysonian** [comment]
Hey so postcss-preset-env includes autoprefixer, good to know.

**Pull request merged**
