### PR TITLE
Artist pages

### PR DESCRIPTION
**Pull request by lmccart**
round of artist page updates with new assets and content. I think this is ready for the artists to review. just missing blaine and leming who have not responded. and I assume @hsab is doing his own page?

### CODE REVIEW

**Comment by blerchin** [comment]
Nice!
I am noticing a couple issues:

- Leading for names on home page has become very large
Screen Shot 2020-05-26 at 1 54 20 PM

- Awkward initial view of vimeo embeds on Graham's page
- Very long load time for Graham's main image. Might be unavoidable but we should look into disabling the lazy-loader here and using progressive encoding so users can "see" the image progress as it's loading.
- Images have no padding and are not aligned with text on Erin's page (possibly intentional?)

**Comment by lmccart** [comment]
thanks @blerchin 

* Leading for names on home page has become very large 
- [x] Don't know where this came from, I didn't think I touched it but I will look around!

* Awkward initial view of vimeo embeds on Graham's page
- [ ] This one is due to Graham having an awkward cover image for his video (the aspect of the cover doesn't match the video). I'll ask him to update.

* Images have no padding and are not aligned with text on Erin's page (possibly intentional?)
- [x] Misalignment is intended, but it is missing image padding. I'll add this.

* Very long load time for Graham's main image. Might be unavoidable but we should look into disabling the lazy-loader here and using progressive encoding so users can "see" the image progress as it's loading.
- [x] I think I will need some help with this one

**Comment by blerchin** [comment]
I pushed an update disabling the lazy loader for Graham's image. Looks like the image conversion is already setup with progressive encoding, yay!
It's a judgment call whether it's better than seeing the blurred image. IMO seeing some movement is better than the blurred image that just stays the same for 30s or more until the image loads.

**Comment by lmccart** [comment]
Cool, thanks. I think this is ready to merge if it looks good to you.

**Review by blerchin — APPROVED** [review]
Looks good!

**Comment by hsab** [comment]
@lmccart  yes I will tc of my page. 
@blerchin I still wonder if netlify has libvips compiled against libimagequant which drastically improves png compression while maintaining a visually imperceptible quality. Since we are statically building, I could build on my end and on Thrus and commit to a new branch. I have the libs properly setup locally.

**Comment by blerchin** [comment]
@hsab would be great if we can reduce file size!
I think this might be the only PNG on the site, certainly the only one that's so large. If so, might be better to render it locally then commit it into the public folder so we don't have to deal with a manual build process.

**Comment by lmccart** [comment]
just wanted to mention, this is not the final image. it's the same dimensions (and likely around the same file size). so if there is any compression step, this will need to be repeated when we have the final file.

**Comment by hsab** [comment]
@blerchin, I gave that idea a try, ironically sharp ends up increasing the file size. If you actually look at the original and what ends up in the website, Graham's pngs sometime get larger. The smallest I brought them down to was ~900kb with quant. Otherwise they went up to 2.7MB. We could reduce them even more at the cost of quality

**Comment by blerchin** [comment]
@hsab I was suggesting to process them with quant, put in public folder and link the old fashioned way (no webpack require) which should bypass sharp. Alternatively, we could set up a rule in webpack to serve files with a certain suffix with file-loader so they will bypass sharp but still get cachebusters.

**Comment by hsab** [comment]
That's a good idea. Since Graham's the only one proponent let's  wait until
he's got his images finalized.

**Pull request merged**
