### PR TITLE
fix padding

### PR DESCRIPTION
**Pull request by hsab**
Fixes the info margin issues on resolution <375px (iPhone 5,6,7,8 )

### CODE REVIEW

**Review by dalena — APPROVED** [review]
Thanks for taking care of this for mobile

**Comment by blerchin** [comment]
nicer fix is much nicer! 👏

**Comment by blerchin** [comment]
netlify is being weird and seems not to have reported the successful build. I just retried it.

**Comment by hsab** [comment]
> netlify is being weird and seems not to have reported the successful build. I just retried it.

ty

**Comment by blerchin** [comment]
this is live now, btw :]

**Pull request merged**
