### PR TITLE
Each child in a list should have a unique key prop.

### PR DESCRIPTION
**Pull request by hsab**
Fixing the react error

### CODE REVIEW

**Comment by brysonian** [comment]
Ack sorry i missed that. just pushed up a tweak. Using the array index is fine for this, but best practice is to use something that is unique to the data. Really only an issue if you have a situation where you want to re-render the array after shuffling the order.

**Comment by hsab** [comment]
thank you chandler! also thanks for all the tips. this ecosystem is a whole world on its own.
I can't review/approve but this is looking good.

**Comment by brysonian** [comment]
It is nearly pythonic in its idiosyncrasies, and takes forever to suss them all out. But it is a great way to build a site IMO.

**Review by blerchin — APPROVED** [review]
👍 slug as key 

btw feel @brysonian @hirad feel free to approve each other's PRs. I don't need to be the sole arbiter for this stuff. Approval rules are there just to discourage solo decision-making and so we have some level of accountability.

**Comment by hsab** [comment]
Yeah. I was wondering if you commit to someone else's PR can you still approve?

**Comment by blerchin** [comment]
> Yeah. I was wondering if you commit to someone else's PR can you still approve?

I think so, yeah. Pretty sure it just has to be approved by someone other than the clicker of the merge button.

**Pull request merged**
