### PR TITLE
Optimize animation on low-performance devices

### PR DESCRIPTION
**Pull request by blerchin**

### CODE REVIEW

**Comment by hsab** [comment]
looks great. Should we have this run constantly? Or should it profile for a certain period of time and then stop?

**Comment by blerchin** [comment]
@hsab I'll profile it on my iPad 2 (which btw can now run the site with acceptable performance 😱 ) and see if it takes more than a couple ms

**Comment by hsab** [comment]
Fair enough.

"which btw can now run the site with acceptable performance" was this in light of fps profiling or some other change?

**Review by hsab — APPROVED** [review]

**Comment by blerchin** [comment]
FPS polling makes it manageable. By "acceptable" I don't mean good. The animation runs at 3fps. But when you click a blob the navigation happens quickly. The blobs take some time to settle into their collapsed positions, but meanwhile scrolling around the page and even playing videos works fine.

**Comment by blerchin** [comment]
I think we can leave the fps polling in place. On the iPad 2 it takes .7ms. Should be several orders of magnitude faster on a modern device.

**Comment by hsab** [comment]
Makes sense. This lgtm. Merge as you see fit.

**Comment by hsab** [comment]
Also it must be and ios thing.  Here's how it looks on my device

https://www.youtube.com/watch?v=DNpA7DzLr5E

**Comment by blerchin** [comment]
@hsab It's not really an iOS thing. it's a 5 year old device thing. Runs very smoothly on my 11 pro..

**Comment by hsab** [comment]
yea just realized 6s came out in 2015. Time goes by fast!

**Comment by blerchin** [comment]
Miles and I are tying to figure out if we can eke out any more performance improvements, but if there's no low-hanging fruit I'll go ahead and merge this.

**Comment by hsab** [comment]
Hey pushed a commit that fixes #87. Not performance related bu blob related. Didn't think a new branch would be needed.

**Comment by blerchin** [comment]
@mileshiroo and I figured out that the lag is largely driven by the gradient, and secondarily by shadow blur. With both of these disabled we get a dramatic increase in frame rate.

We can't continuously adapt to fps because of the awful flashing effect that occurs if framerate is hovering around the threshold.
Current best solution seems to be to start with effects enabled, then disable for the rest of the session if fps drops below 40 after an initial boot up period.

@hsab what do you think about this solve?

**Comment by hsab** [comment]
It's a reasonable compromise. I don't have an ios device around but trust your judgments. I actually noticed the fps drop once when I really cranked up the shadow blur. I don't know why it didn't occur to me to mention it. It could have save you some time. Anywas... this LGTM

**Comment by blerchin** [comment]
Screen Shot 2020-05-27 at 9 48 02 PM
cool, here's how it looks without the gradient. Not sure if it's the right color to use.

**Comment by hsab** [comment]
@blerchin can we swap the colors? Set the main color as the outer edge. It looks a bit uniform

**Comment by blerchin** [comment]
Screen Shot 2020-05-27 at 10 04 04 PM
I just switched it to this. is that what you mean by outer edge?

**Comment by hsab** [comment]
Indeed

**Comment by hsab** [comment]
@mileshiroo  @blerchin on another note, does opacity also affect the performance? Since we have the names on the blobs now, wondering if we could ditch it to gain a boost

**Comment by blerchin** [comment]
@hsab not sure, haven't tested. But I am seeing an increase from ~20 to 60fps in the simulator with the gradient removed so I don't feel super motivated to keep optimizing.

**Comment by blerchin** [comment]
OK, I'm gonna go ahead and merge this. Based on testing in browserstack, there seem to be some optimizations in iOS 13 that make it run a lot better. So only latest and greatest hardware (iPhone X or better) are likely to see the gradients. But everyone else will get a smooth animation so it's all good.

On Android it seems like Galaxy S10/Pixel 2 and better can handle the effects.

**Comment by hsab** [comment]
> OK, I'm gonna go ahead and merge this. Based on testing in browserstack, there seem to be some optimizations in iOS 13 that make it run a lot better. So only latest and greatest hardware (iPhone X or better) are likely to see the gradients. But everyone else will get a smooth animation so it's all good.
> 
> On Android it seems like Galaxy S10/Pixel 2 and better can handle the effects.

This is great. Thank you Ben

**Pull request merged**
