### PR TITLE
Updates to Ben's page

### PR DESCRIPTION
**Pull request by blerchin**
Modifications to shared components:
- exposes more options to the `<Video>` component to allow it to use `autoPlay` and `loop`
- sets zIndex:0 on `<ProjectCover>` contents when scrolled to the top of the page, so contents are playable

### CODE REVIEW

**Review by hsab — COMMENTED** [review]
Yes to your commit

**Comment by blerchin** [comment]
> Yes to your commit

Thanks, can you re-review with Approved checked ^_^

**Review by hsab — APPROVED** [review]

**Comment by hsab** [comment]
> > Yes to your commit
> 
> Thanks, can you re-review with Approved checked ^_^

I wonder why it insisted for me to comment :laughing:

**Comment by blerchin** [comment]
> > > Yes to your commit
> > 
> > 
> > Thanks, can you re-review with Approved checked ^_^
> 
> I wonder why it insisted for me to comment 😆

I do appreciate the enthusiasm in any case!

**Comment by dalena** [comment]
Loving your project page @blerchin! Also the documentation loop of water work is awesome. You should photoshop a tiny person into the image for scale 😆

**Comment by blerchin** [comment]
> Loving your project page @blerchin! Also the documentation loop of water work is awesome. You should photoshop a tiny person into the image for scale 😆

thanks :blush: I love the idea of these things being huge

**Pull request merged**
