### PR TITLE
Styling round one

### PR DESCRIPTION
**Pull request by dalena**
This pull request is styling the colors of blobs, the NN title, made the margins consistent between project component and nav. Added button and link styling. Added and changed typefaces on site.  Apologies in advance if i was supposed to keep to one branch. please let me know best git practices.

### CODE REVIEW

**Comment by hsab** [comment]
Not a big fan of the colors on project headers. Makes it a bit overwhelming and inconsistent. Also feels like too much/many colors.  Other than that really like the new blob colors and the typeface

**Comment by blerchin** [comment]
I have to agree with Hirad on the header colors. The dimensionality of the blobs is really nice with this update.

**Comment by hsab** [comment]
@blerchin if this is ok with you it lgtm.

**Review by hsab — APPROVED** [review]

**Comment by blerchin** [comment]
Looks good! I think there is a typekit tag in `public/index.html`. If we're no longer using those fonts we should get rid of that.

**Comment by hsab** [comment]
Seems like we're using that one for the body text. Liberation Sans @dalena ?

**Comment by dalena** [comment]
yeah we are using it for body. Was only available on adobe typekit

**Pull request merged**
