### PR TITLE
Add names to blobs on mobile

### PR DESCRIPTION
**Pull request by blerchin**
This PR adds artist names overlaid on blobs for viewports < 769px.
#18 

@hsab let me know what you think about the implementation.
I think it could be improved visually by centering the name on the centroid rather than "point", but haven't looked into what it would take to implement it.

### CODE REVIEW

**Comment by blerchin** [comment]
I tried using mapbox's `polylabel` algorithm to get the best point for a label. Unfortunately it seems like there's too much stochastic variation for it to be useful. With type changes I think it is looking pretty good now.

**Comment by hsab** [comment]
@blerchin I like what you've done and the implementation looks great to me. At this point I wouldn't worry about the perfect centering. What I'm concerned with is that visually it looks really bad! And I don't mean it as you've done a bad job, not at all, what I mean is that the idea while good on paper in practice is visually unpleasant. 

I have an alternative in mind. Which I think is more subtle and elegant and visually nonintrusive. 




Two arrows at the top that allow toggling between artists. Everytime you click one, it will highlight the prev/next artist from the config, triggering the hover state. I don't think we need to have them on collapse. 

Between them, we could show a small informative text:
"Tap and drag to interact, click to view." 

@dalena  @blerchin 
What do you think?

**Comment by blerchin** [comment]
@hsab I can't say I agree that it looks "bad". Maybe not quite as slick as our desktop version but I think it's aesthetically fine. It is also what we set out to achieve in the mockups two weeks ago. I feel pretty strongly we should not be making major changes this close to the show.

The interaction you've mocked up looks difficult to implement, and I am not convinced it will be very user-friendly. At least with the names on blobs it is very easy to get where you want to go. Which is the most important thing for a nav interface.

**Comment by hsab** [comment]
I guess we disagree there. Objectively it doesn't look good. Like what is this?

And I would bet that if you showed it to design folks a majority of whom would agree with me. 

If the arrows are difficult to implement, I rather have a very short tour on mobile that introduces the interaction, rather than pumping the visual field with text.  There's [reactour](https://github.com/elrumordelaluz/reactour) and [joyride](https://github.com/gilbarbara/react-joyride) which I think would be a quick sec to get up and running.

**Comment by blerchin** [comment]
@hsab what if we invested that dev time instead in shrinking the labels to fit the blobs. Which seems to be your objection if I understand you? Should be doable to shrink based on the extent of the blobs.

We have had an open issue for adding the labels to blobs for 11 days. This was based on an earlier conversation with the cohort where we established it was important to be able to see all names and click them on mobile. If you had objections you should have raised them at that point.

**Comment by hsab** [comment]
Raising objections during dev is not uncommon. Being dismissive of them is not uncommon either.  I was never a fan of the idea, so I never tackled that issue. I did voice this in our communication channel as a response to Erin, visible to all. Regardless, I'm voicing my opinion, again, now, and I have the right to do so. 

Nevertheless, let's just roll with the idea, although I sincerely think there are much much better alternatives. 

We could use the [`position`](http://paperjs.org/reference/path/#position) of the `path`  rather than the `ball` which by default "is the `rectangle.center` of the item’s `bounds` rectangle." This seems to be working fine for calculating the gradients here: https://github.com/blerchin/dma-20-mfa-show/blob/3d5fe829e5103fa4b8d933d7c54b4baddeb8ff4d/src/BlobField/ball.js#L81

On another note, if I spent time adding the arrows would you still object to it? Our problem was legibility and I think as a solution the arrows solve it gracefully without drastically maximalizing reliance on text.

**Comment by blerchin** [comment]
@hsab good call on using `path.position`. That is a significant improvement. Combined with adjusting type size for each blob I think we could contain the text entirely.

With regard to prototyping other options, you can use your time as you see fit. As far as merging it into the project I would need to be convinced A) our current accepted design is a problem and B) the swiping version is a good UX for navigating the site. When push comes to shove people being able to find and view our artwork is much more important than the pixel-perfectness of the site.

Side-note: I would appreciate it you would refrain from phrasing concerns as "this is objectively bad." It makes it extremely difficult to have productive conversations vs. expressing specific issues or ways something could be improved.

**Comment by hsab** [comment]
Regarding your side-note, I did provide two different alternatives. I mentioned that it is visually unpleasant and intrusive, overtly relies on text, looks good on paper but not in practice. I provided screenshot of the issue and did mockups for alternatives. Also pointed how to elegantly fix the positioning issue without overengineering and adding extra dependencies. Not sure how much of a restraint these are on having a productive conversation in comparison to "If you had objections you should have raised them at that point." 😆

But feel free to focus on the "objectively bad". To me it feels like a tactic of antagonization that intentionally disregards so much of what has been said. I'm not getting paid to do this and my concerns are neither masochistic nor malintended, they come from good intention and care. 

PS. "As far as merging it into the project **I** would need to be convinced" The "I" there seems a bit authoritative. At the end of the day, whatever I've contributed that had significant impacts, I've discussed with the cohort and asked for a democratic process of approval. These proposals would not be any different from that.

Anyways.. this looks good. I'm gonna go ahead and approve but I do think a smaller font would be less intrusive. I tried these vals with good results, but I'll leave it to you to incorporate if you want to.

Thanks for taking care of this. 
```
  updateFont() {
    this.label.fontSize = document.body.clientWidth * 0.03;
    this.label.leading = document.body.clientWidth * 0.035;
  }
```

**Review by hsab — APPROVED** [review]

**Comment by blerchin** [comment]
I don't want to get too bogged down with this. Let's merge this so we have a workable option. Time permitting we can pursue design changes.

Perhaps I am being authoritarian. I have been through enough product launches to know that last minute design changes are the enemy of shipping working code on time. We still have a number of crucial issues to resolve so that we have something that can go live on Friday. That includes browser testing which will likely take a substantial amount of time, given the complexity of this site.

**Comment by lmccart** [comment]
Hey you two, don't want to get in the middle of your conversation. Just want to say that I feel the point about all of your work coming from "good intention and care". Nothing is more obvious to me working with you all over the last few weeks on this, how much effort, time, care, and attention you are each putting into it. I know you all know that, but it's worth saying again. It is inspiring, and something to feel proud of. I hope your classmates see it, too. The last stretch is hard, but it's very close. It is significant what you're making together here.

**Comment by hsab** [comment]
> I don't want to get too bogged down with this. Let's merge this so we have a workable option. Time permitting we can pursue design changes.

Sounds good. There's a small issue with hovering over the label that  breaks the default behavior of fades and bg title switching. 

I'm just gonna comment here to remember. Let's marge and I will tc of this later. 
```
			currBall.label.onMouseEnter = this.pathOnMouseEnter.bind(this);
			currBall.label.onMouseLeave = this.pathOnMouseLeave.bind(this);
```
https://github.com/blerchin/dma-20-mfa-show/blob/28a7aa43aa9a88cbea454db01d92f0d73af3536e/src/BlobField/blobs.js#L111-L112

TODO: 

- add idx to label,
- `if (this.balls[i].path !== event.target && this.balls[i].label !== event.target )` need to think about this more. Maybe switch from path/label checking to `event.target.idx !== this.ball.idx`

**Pull request merged**
