### PR TITLE
Styling Round Five

### LINKED ISSUE #123: Large top margin on Berfin's Page
Screenshot_20200529_211245

### PR DESCRIPTION
**Pull request by hsab**
Just initing a new PR for #123 
Too tired to look into this rn.

Screenshot_20200529_211245

### CODE REVIEW

**Comment by blerchin** [comment]
It seems like there are some weird edge cases where the `paddingBottom` sizing does not work very well. Trying this solution, which will need to be thoroughly tested across the site for side effects.

Edit: thought this through further, and I suspect the problem (and why it's showing up in this example) is this:
`paddingBottom` is relative to the width of the parent element. Because CSS is perfect and always makes sense. In most cases the `responsiveVimeo` container takes up 100% of its parent width so this is effectively synonymous with setting height as a % of the element's width. However since we set `max-width` for `responsiveVimeo` on this page, the height becomes relative to the wrong value.

**Comment by blerchin** [comment]
This CSS solution seems to validate my theory. It should be relatively safe to swap in.

**Comment by hsab** [comment]
Thank you @blerchin for tc of this. Minor detail but ProjectHeader margin issue seems to be back for Graham!

**Comment by hsab** [comment]
Also I can't approve this, if you can't either lets ask @dalena

**Comment by hsab** [comment]
For reference, since might be resolution dependent 
Screenshot_20200530_141554

**Comment by blerchin** [comment]
@hsab Oooh, more fun CSS trivia! `position:relative` is inherited, so while the header should seemingly be positioned relative to that, in fact it is sized relative to a child container that wraps the content. If we make that container `static`, all is well :]

**Comment by blerchin** [comment]
I'm going to add a bouncing arrow to this PR to encourage scrolling. Then it should be good to go.

**Comment by blerchin** [comment]
hmm actually that positioning change had pretty significant consequences for other pages on the site. might need to reconsider. 

Edit: jk lol. I just hadn't seen the site in such a wide frame before.

**Review by dalena — APPROVED** [review]
sorry it took so long to review this. my phone was accidentally on do not disturb

**Comment by blerchin** [comment]
@dalena all good :) I would have used my admin superpowers if it was urgent, but generally like to have additional eyes on things before merging.

**Pull request merged**
